# -*- coding: utf-8 -*-
"""TF MB-2025-P2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UuFF3R2LPOLA6E5qnNKYIK0_BPbFkXV

**TRABAJO FINAL DE GRADO**

PARTE 2

**“Gemelo Digitale para evaluar el impacto de la sequía meteorologica en el  valor de la tierra rural**


**Macarena Benitez**

####Dependencias
"""

# Librerías geoespaciales, visualización y conexión con Earth Engine
!pip install earthengine-api geemap folium geopandas shapely rasterio rioxarray --quiet

"""- Instalación de la librería Contextily para mapas base"""

!pip install contextily

"""- Instalación de librerías geoespaciales (GeoPandas, OWSLib, Folium)"""

!pip install geopandas owslib folium --quiet

"""- Instalación del stack geoespacial en Python"""

!pip install geopandas folium owslib shapely

"""- Instalación de dependencias de machine learning (XGBoost)"""

!pip install xgboost

"""####Librerias"""

# =========================
# Core / sistema
# =========================
import os
import gc
import io
import re
import csv
import time
import warnings
import unicodedata
import xml.etree.ElementTree as ET

warnings.filterwarnings("ignore")

# =========================
# Data science
# =========================
import numpy as np
import pandas as pd
from scipy.stats import ttest_ind, pearsonr

# =========================
# Machine Learning
# =========================
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

import xgboost as xgb
import statsmodels.formula.api as smf

# =========================
# HTTP / requests robusto
# =========================
import requests
from urllib3.util import Retry
from requests.adapters import HTTPAdapter

# =========================
# Geoespacial (vector + raster)
# =========================
import geopandas as gpd
import shapely
from shapely.geometry import Point, shape, box
from shapely.ops import unary_union
from shapely import make_valid
from shapely import voronoi_polygons

import rasterio
import rioxarray
import contextily as ctx

# =========================
# OGC / IDECOR (WMS/WFS/WCS)
# =========================
from owslib.wfs import WebFeatureService
from owslib.wms import WebMapService
from owslib.wcs import WebCoverageService

# =========================
# Earth Engine / geemap
# =========================
import ee
import geemap

# =========================
# Visualización
# =========================
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.ticker as ticker
from matplotlib.ticker import LogLocator, FuncFormatter, MaxNLocator
from matplotlib.patches import Patch, Rectangle, FancyBboxPatch, FancyArrowPatch

import seaborn as sns

# =========================
# Folium (mapas)
# =========================
import folium
from folium.plugins import MarkerCluster, Search
from branca.element import Element, Template, MacroElement
from branca.colormap import LinearColormap

# =========================
# UI / notebooks (Colab + widgets)
# =========================
from IPython.display import display, HTML, Markdown, IFrame, clear_output
import ipywidgets as widgets
import gradio as gr
from google.colab import files

"""####Dataset

Es una colección organizada de datos que se utiliza para analizar, entrenar modelos o generar información.
"""

# URL RAW del archivo en GitHub
url = "https://raw.githubusercontent.com/MacarenaBenitez/Trabajo-Final-de-Grado-IA-MB/main/dataset_integrado_VUR_pesos_PDSI_IP%20(1).csv"

"""Informacion de dataset"""

df = pd.read_csv(
    url,
    sep=",",
    engine="python",
    quoting=csv.QUOTE_NONE,
    on_bad_lines="skip"
)

print("✔ Dataset cargado")
print("Columnas originales:")
print(df.columns)

df = df.drop(columns=["IP_prom_simple"])

"""####Datos de IDECOR"""

# Datos de IDECOR
class IDECORAPI:
    def __init__(self):
        self.wfs_url = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/wfs"
        self.wms_url = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/wms"
        self.wcs_url = "https://idecor-wcs.mapascordoba.gob.ar/geoserver/idecor/wcs"
        self.wmts_url = "https://idecor-tiles.mapascordoba.gob.ar/geoserver/gwc/service/wmts"

    # Obtener lista de capas WFS disponibles
    def get_wfs_layers(self):
        wfs = WebFeatureService(url=self.wfs_url, version="1.1.0")
        return list(wfs.contents.keys())

    # Descargar una capa WFS como GeoDataFrame
    def get_wfs_layer(self, layer_name, srs="EPSG:4326"):
        url = (
            f"{self.wfs_url}?service=WFS&version=1.0.0&request=GetFeature"
            f"&typeName={layer_name}&outputFormat=application/json&srsName={srs}"
        )
        return gpd.read_file(url)

# Crear instancia de la API
api = IDECORAPI()
# --- Listar todas las capas disponibles ---
layers = api.get_wfs_layers()

print(f" Total de capas disponibles: {len(layers)}\n")
for i, layer in enumerate(layers, start=1):
    print(f"{i:03d}. {layer}")

"""####Departamento"""

# 1. Descargar capa de departamentos (WFS)
departamentos = api.get_wfs_layer("idecor:departamentos")

# 2. Buscar de manera  automática la columna que contiene 'UNIÓN'
col_union = None
for col in departamentos.columns:
    if departamentos[col].astype(str).str.upper().str.contains("UNIÓN").any():
        col_union = col
        break

if col_union is None:
    raise ValueError("No se encontró ninguna columna con el valor 'UNIÓN'.")

# 3. Filtrar solo el Departamento Unión
union = departamentos[departamentos[col_union].astype(str).str.upper() == "UNIÓN"].copy()

print(union.head())

"""#####Pedania"""

# ================= Parámetros =================
DEPTO_CODIGO = 36           # código del depto UNIÓN
DEPTO_NOMBRE = "UNION"      # respaldo por nombre (sin acentos, mayúsculas)
EPSG_POSGAR4 = 5348

WFS_ENDPOINTS = [
    "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/wfs",
    "https://idecor-ws.mapascordoba.gob.ar/geoserver/wfs",
    "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/pedania/wfs",
]

LAYER_CANDIDATOS_DEPARTAMENTO = ["idecor:departamento", "idecor:departamentos"]
LAYER_CANDIDATOS_PEDANIAS     = ["idecor:pedania", "idecor:pedanias"]

def normalizar_txt(s):
    if pd.isna(s):
        return s
    s = str(s).upper().strip()
    s = unicodedata.normalize('NFD', s).encode('ascii', 'ignore').decode('utf-8')
    return s

def try_get_wfs_layer(type_candidates, srs="EPSG:4326", timeout=60):
    last_err = None
    for url in WFS_ENDPOINTS:
        for type_name in type_candidates:
            try:
                params = dict(
                    service="WFS",
                    version="2.0.0",
                    request="GetFeature",
                    typeNames=type_name,
                    srsName=srs,
                    outputFormat="application/json",
                )
                r = requests.get(url, params=params, timeout=timeout)
                r.raise_for_status()
                data = r.json()
                feats = data.get("features", [])
                if not feats:
                    continue
                rows = []
                for f in feats:
                    props = f.get("properties", {}) or {}
                    geom  = f.get("geometry")
                    if geom is None:
                        continue
                    props["geometry"] = shape(geom)
                    rows.append(props)
                if rows:
                    return gpd.GeoDataFrame(rows, geometry="geometry", crs=srs)
            except Exception as e:
                last_err = e
                continue
    raise RuntimeError(f"No pude descargar la capa. Último error: {last_err}")

# ================ Flujo principal =================
#  Departamentos
departamentos = try_get_wfs_layer(LAYER_CANDIDATOS_DEPARTAMENTO, srs="EPSG:4326")

# Preferir filtro por CÓDIGO = 36
depto_union = pd.DataFrame()
if "codigo" in departamentos.columns:
    cod = pd.to_numeric(departamentos["codigo"], errors="coerce")
    depto_union = departamentos.loc[cod.eq(DEPTO_CODIGO)].copy()

# Respaldo: por nombre normalizado "UNION"
if depto_union.empty and "nombre" in departamentos.columns:
    dep = departamentos.copy()
    dep["_nom_"] = dep["nombre"].apply(normalizar_txt)
    depto_union  = dep.loc[dep["_nom_"].eq(DEPTO_NOMBRE)].drop(columns=["_nom_"]).copy()

if depto_union.empty:
    raise ValueError("No se encontró el departamento UNIÓN ni por código 36 ni por nombre.")

#  Pedanías
pedanias = try_get_wfs_layer(LAYER_CANDIDATOS_PEDANIAS, srs="EPSG:4326")

#  Reproyectar y recortar al depto UNIÓN (código 36)
depto_union_proj  = depto_union.to_crs(EPSG_POSGAR4)
pedanias_proj     = pedanias.to_crs(EPSG_POSGAR4)

# Recorte espacial (pedanías que INTERSECTAN el depto 36)
pedanias_union = gpd.sjoin(
    pedanias_proj,
    depto_union_proj[["geometry"]],
    how="inner",
    predicate="intersects"
).drop(columns=["index_right"])

# 4) Columnas útiles
cols_preferidas = [c for c in ["id", "nomenclatura", "nombre", "geometry"] if c in pedanias_union.columns]
if cols_preferidas:
    pedanias_union = pedanias_union[cols_preferidas].copy()

"""####Tabla de datos"""

display(df)

"""###Capas

Radios urbanos
"""

# --- Parámetros ---
LAYER_RADIOS = "idecor:radios_urbanos"
EPSG_POSGAR4 = 5346
DEPTO_OBJETIVO = "UNION"  # sin acentos y en mayúsculas

# --- Helper: normalizar texto (mayúsculas y sin acentos) ---
def normalizar_txt(s):
    if pd.isna(s):
        return s
    s = str(s).upper().strip()
    s = unicodedata.normalize('NFD', s).encode('ascii', 'ignore').decode('utf-8')
    return s

# --- 1) Descargar radios urbanos (WFS) ---
api = IDECORAPI()
radios_urbanos = api.get_wfs_layer(LAYER_RADIOS)

"""Red vial"""

# ================= Parámetros =================
DEPTO_OBJETIVO = "UNION"
EPSG_POSGAR4   = 5346

# --- Endpoints WFS  ---
WFS_REGIONAL   = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/regionales/wfs"
WFS_PROVINCIAL = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/red_vial_provincial/wfs"
WFS_NACIONAL   = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/red_vial_nacional/wfs"

# --- typeNames esperados (ajusta si difieren en el servidor) ---
LAYER_REGIONAL_CAND   = ["idecor:regionales"]
LAYER_PROVINCIAL_CAND = ["idecor:red_vial_provincial", "idecor:redvial_provincial"]
LAYER_NACIONAL_CAND   = ["idecor:red_vial_nacional", "idecor:redvial_nacional"]

# --- Para obtener el polígono de departamentos ( el workspace WFS genérico del IDECOR) ---
WFS_IDECOR_WORKSPACE = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/wfs"
LAYER_DEPARTAMENTO_CAND = ["idecor:departamento", "idecor:departamentos"]

# ================= Helpers =================
def normalizar_txt(s):
    if pd.isna(s):
        return s
    s = str(s).upper().strip()
    s = unicodedata.normalize('NFD', s).encode('ascii', 'ignore').decode('utf-8')
    return s

def get_wfs_layer(url, type_name, srs="EPSG:4326", timeout=60):
    """Descarga una capa WFS (GeoServer) como GeoDataFrame."""
    params = dict(
        service="WFS",
        version="2.0.0",
        request="GetFeature",
        typeNames=type_name,
        srsName=srs,
        outputFormat="application/json",
    )
    r = requests.get(url, params=params, timeout=timeout)
    r.raise_for_status()
    data = r.json()
    records = []
    for f in data.get("features", []):
        props = f.get("properties", {}) or {}
        geom = f.get("geometry")
        if geom is not None:
            props["geometry"] = shape(geom)
            records.append(props)
    return gpd.GeoDataFrame(records, geometry="geometry", crs=srs)

def try_first_ok(url, candidates):
    """Prueba typeNames candidatos hasta que uno funcione (devuelve GeoDataFrame y el nombre usado)."""
    last_err = None
    for tn in candidates:
        try:
            gdf = get_wfs_layer(url, tn, srs="EPSG:4326")
            if not gdf.empty:
                print(f" Descargada '{tn}' desde {url} | {len(gdf)} entidades")
                return gdf, tn
        except Exception as e:
            last_err = e
    # Si todas fallaron, levantamos el último error
    raise RuntimeError(f"No pude descargar ninguna variante en {url}. Último error: {last_err}")

# ================= Flujo =================
# 1) Departamento UNIÓN
deptos, tn_depto = try_first_ok(WFS_IDECOR_WORKSPACE, LAYER_DEPARTAMENTO_CAND)
if "nombre" not in deptos.columns:
    raise KeyError(f"No encuentro columna 'nombre' en departamentos. Columnas: {list(deptos.columns)}")
deptos["_nombre_norm_"] = deptos["nombre"].apply(normalizar_txt)
depto_union = deptos[deptos["_nombre_norm_"] == DEPTO_OBJETIVO].drop(columns="_nombre_norm_")
if depto_union.empty:
    raise ValueError("No se encontró el departamento 'UNIÓN' en la capa de departamentos.")
print(" Departamento UNIÓN obtenido.")

# Reproyectamos a sistema métrico local
depto_union_5348 = depto_union.to_crs(EPSG_POSGAR4)

# 2) Red vial REGIONAL (recorte a UNIÓN)
regional, tn_reg = try_first_ok(WFS_REGIONAL, LAYER_REGIONAL_CAND)
regional_5348 = regional.to_crs(EPSG_POSGAR4)
# clip robusto para líneas (si falla clip por topología, usar sjoin/intersects)
try:
    regional_union = gpd.clip(regional_5348, depto_union_5348)
except Exception:
    regional_union = gpd.sjoin(regional_5348, depto_union_5348[["geometry"]], how="inner", predicate="intersects").drop(columns="index_right")
print(f"  Regional en UNIÓN: {len(regional_union)}")

# 3) Red vial PROVINCIAL (recorte a UNIÓN)
provincial, tn_prov = try_first_ok(WFS_PROVINCIAL, LAYER_PROVINCIAL_CAND)
provincial_5348 = provincial.to_crs(EPSG_POSGAR4)
try:
    provincial_union = gpd.clip(provincial_5348, depto_union_5348)
except Exception:
    provincial_union = gpd.sjoin(provincial_5348, depto_union_5348[["geometry"]], how="inner", predicate="intersects").drop(columns="index_right")
print(f"  Provincial en UNIÓN: {len(provincial_union)}")

# 4) Red vial NACIONAL (recorte a UNIÓN)
nacional, tn_nac = try_first_ok(WFS_NACIONAL, LAYER_NACIONAL_CAND)
nacional_5348 = nacional.to_crs(EPSG_POSGAR4)
try:
    nacional_union = gpd.clip(nacional_5348, depto_union_5348)
except Exception:
    nacional_union = gpd.sjoin(nacional_5348, depto_union_5348[["geometry"]], how="inner", predicate="intersects").drop(columns="index_right")
print(f"  Nacional en UNIÓN: {len(nacional_union)}")

"""Hidrologia"""

# ================= Parámetros globales =================
EPSG_POSGAR4   = 5346
DEPTO_OBJETIVO = "UNION"  # escribir sin acentos y en mayúsculas

# --- Endpoints WFS ---
WFS_WS          = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/wfs"
WFS_ACUEDUCTOS  = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/acueductos/wfs"
WFS_CURSOS      = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/cursos_agua/wfs"
WFS_EMBALSES    = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/embalses/wfs"
WFS_CUERPOS     = "https://idecor-ws.mapascordoba.gob.ar/geoserver/idecor/cuerpos_de_agua_naturales_aprhi/wfs"

# --- typeNames candidatos (pueden variar levemente) ---
TN_DEPARTAMENTO = ["idecor:departamento", "idecor:departamentos"]
TN_ACUEDUCTOS   = ["idecor:acueductos"]
TN_CURSOS       = ["idecor:cursos_agua", "idecor:cursosagua"]
TN_EMBALSES     = ["idecor:embalses"]
TN_CUERPOS      = ["idecor:cuerpos_de_agua_naturales_aprhi", "idecor:cuerpos_agua_naturales"]

# ================= Helpers =================
def normalizar_txt(s):
    if pd.isna(s):
        return s
    s = str(s).upper().strip()
    s = unicodedata.normalize('NFD', s).encode('ascii', 'ignore').decode('utf-8')
    return s

def _get_wfs_layer(url, type_name, srs="EPSG:4326", timeout=60):
    """Descarga una capa WFS (GeoServer) -> GeoDataFrame."""
    params = dict(
        service="WFS",
        version="2.0.0",
        request="GetFeature",
        typeNames=type_name,
        srsName=srs,
        outputFormat="application/json",
    )
    r = requests.get(url, params=params, timeout=timeout)
    r.raise_for_status()
    data = r.json()
    records = []
    for f in data.get("features", []):
        props = f.get("properties", {}) or {}
        geom = f.get("geometry")
        if geom is None:
            continue
        props["geometry"] = shape(geom)
        records.append(props)
    gdf = gpd.GeoDataFrame(records, geometry="geometry", crs=srs)
    return gdf

def _try_first_ok(url, candidates):
    """Prueba typeNames candidatos y devuelve (gdf, type_name_usado)."""
    last_err = None
    for tn in candidates:
        try:
            gdf = _get_wfs_layer(url, tn, srs="EPSG:4326")
            if not gdf.empty:
                print(f" '{tn}' desde {url} | {len(gdf)} entidades")
                return gdf, tn
        except Exception as e:
            last_err = e
            continue
    raise RuntimeError(f"No pude descargar en {url}. Último error: {last_err}")

# ================= Mini-API =================
class IDECORHydroAPI:
    def __init__(self, depto_objetivo: str = DEPTO_OBJETIVO, epsg_out: int = EPSG_POSGAR4):
        self.depto_objetivo = normalizar_txt(depto_objetivo)
        self.epsg_out = epsg_out
        self._depto_gdf_5348 = None  # cache del polígono de depto

    # ---- Departamento (para recortes) ----
    def _get_depto_union(self) -> gpd.GeoDataFrame:
        if self._depto_gdf_5348 is not None:
            return self._depto_gdf_5348

        deptos, _ = _try_first_ok(WFS_WS, TN_DEPARTAMENTO)
        if "nombre" not in deptos.columns:
            raise KeyError(f"No encuentro columna 'nombre' en departamentos: {list(deptos.columns)}")
        deptos["_nombre_norm_"] = deptos["nombre"].apply(normalizar_txt)
        g = deptos[deptos["_nombre_norm_"] == self.depto_objetivo].drop(columns="_nombre_norm_")
        if g.empty:
            raise ValueError(f"No se encontró departamento '{self.depto_objetivo}' en la capa de departamentos.")
        self._depto_gdf_5348 = g.to_crs(self.epsg_out)
        print(f" Departamento '{self.depto_objetivo}' listo para recortes.")
        return self._depto_gdf_5348

    # ---- Descarga genérica + recorte ----
    def _fetch_and_clip(self, url: str, tn_candidates, keep_cols=None) -> gpd.GeoDataFrame:
        gdf, used_tn = _try_first_ok(url, tn_candidates)
        gdf_5348 = gdf.to_crs(self.epsg_out)
        depto_5348 = self._get_depto_union()
        # clip (si falla por geometrías, caemos a sjoin/intersects)
        try:
            clipped = gpd.clip(gdf_5348, depto_5348)
        except Exception:
            clipped = gpd.sjoin(
                gdf_5348,
                depto_5348[["geometry"]],
                how="inner",
                predicate="intersects"
            ).drop(columns="index_right")
        if keep_cols:
            keep = [c for c in keep_cols if c in clipped.columns] + ["geometry"]
            keep = list(dict.fromkeys(keep))  # único y mantener orden
            clipped = clipped[keep]
        print(f"  Recortado '{used_tn}' a '{self.depto_objetivo}': {len(clipped)}")
        return clipped

    # ---- Capas específicas ----
    def acueductos(self) -> gpd.GeoDataFrame:
        return self._fetch_and_clip(WFS_ACUEDUCTOS, TN_ACUEDUCTOS, keep_cols=["id", "nombre"])

    def cursos_agua(self) -> gpd.GeoDataFrame:
        return self._fetch_and_clip(WFS_CURSOS, TN_CURSOS, keep_cols=["id", "nombre", "jerarquia"])

    def embalses(self) -> gpd.GeoDataFrame:
        return self._fetch_and_clip(WFS_EMBALSES, TN_EMBALSES, keep_cols=["id", "nombre", "superficie_ha"])

    def cuerpos_agua_naturales(self) -> gpd.GeoDataFrame:
        return self._fetch_and_clip(
            WFS_CUERPOS,
            TN_CUERPOS,
            keep_cols=["id", "nombre", "tipo", "superficie_ha"]
        )

# ================= Ejemplo de uso =================
if __name__ == "__main__":
    api = IDECORHydroAPI(depto_objetivo="UNION", epsg_out=EPSG_POSGAR4)

    gdf_acueductos = api.acueductos()
    gdf_cursos     = api.cursos_agua()
    gdf_embalses   = api.embalses()
    gdf_cuerpos    = api.cuerpos_agua_naturales()

    print("Resumen:")
    print("  Acueductos:", len(gdf_acueductos))
    print("  Cursos de agua:", len(gdf_cursos))
    print("  Embalses:", len(gdf_embalses))
    print("  Cuerpos de agua naturales:", len(gdf_cuerpos))

"""#### C. Ingenieria de Datos

El objetivo es utilizar el conjunto de datos depurado obtenido en la etapa anterior para identificar parámetros del proceso con un alto grado de correlación con el parámetro objetivo que se desea predecir.

#####Matriz de correlacion de variables
"""

# -------------------------
# Seleccionar variables numéricas
# -------------------------
cols_corr = [
    "valor_pesos",
    "IP_prom_area",
    "PDSI_promedio",
    "anio"
]

# Tomar solo las que existan en el dataset
cols_corr = [c for c in cols_corr if c in df.columns]

df_corr = df[cols_corr].copy()

# -------------------------
# Calcular matriz de correlación
# -------------------------
corr_matrix = df_corr.corr(method="pearson")

# -------------------------
# Visualización
# -------------------------
plt.figure(figsize=(8, 6))
sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    linewidths=0.5
)

plt.title("Matriz de correlación de variables")
plt.tight_layout()
plt.show()

"""#####Coeficiente de correlación entre PDSI y valor de tierra por PEDANIA.

- Pearson: relación lineal. Es decir, ¿Aumenta o disminuye el valor del suelo  a medida que cambia el PDSI?

- Spearman:relación monotónica (no lineal). ¿Cuando el PDSI aumenta o disminuye, el valor del suelo tiende a subir o bajar en forma ordenada, aunque no sea lineal?

######Pearson
"""

from scipy.stats import pearsonr

# =========================
# Formato argentino moneda
# =========================
def fmt_ar(v, dec=2):
    if abs(v) < 0.0000005:
        v = 0
    return f"{v:,.{dec}f}".replace(",", "X").replace(".", ",").replace("X", ".")

def fmt_int_ar(v):
    return f"{v:,}".replace(",", ".")

def fmt_cient_ar(v):
    base, exp = f"{v:.2e}".split("e")
    base = base.replace(".", ",")
    return f"{base}e{exp}"

# -----------------------
# 1) Selección y limpieza
# -----------------------
xcol = "PDSI_promedio"
ycol = "valor_pesos"

df_xy = df[[xcol, ycol]].copy()
df_xy[xcol] = pd.to_numeric(df_xy[xcol], errors="coerce")
df_xy[ycol] = pd.to_numeric(df_xy[ycol], errors="coerce")
df_xy = df_xy.dropna()

# Muestreo
n = 100000
if len(df_xy) > n:
    df_xy = df_xy.sample(n=n, random_state=42)

# -----------------------
# 2) Pearson + recta
# -----------------------
r, p = pearsonr(df_xy[xcol], df_xy[ycol])
m, b = np.polyfit(df_xy[xcol], df_xy[ycol], 1)

# -----------------------
# 3) Tabla de resultados
# -----------------------
tabla_resultados = pd.DataFrame({
    "Variable X": [xcol],
    "Variable Y": [ycol],
    "Coeficiente Pearson (r)": [r],
    "p-value": [p],
    "N observaciones": [len(df_xy)],
    "Pendiente (β)": [m],
    "Intercepto (α)": [b]
})

# -----------------------
# 4) Mostrar tabla formato argentino
# -----------------------
tabla_resultados.style\
    .set_caption("Resultado del análisis de correlación de Pearson")\
    .format({
        "Coeficiente Pearson (r)": lambda v: fmt_ar(v, 4),
        "p-value": fmt_cient_ar,
        "N observaciones": fmt_int_ar,
        "Pendiente (β)": lambda v: fmt_ar(v, 2),
        "Intercepto (α)": lambda v: fmt_ar(v, 2),
    })\
    .set_properties(**{"text-align": "center"})

"""La variable X, PDSI_promedio, es la variable explicativa en el análisis. Este índice refleja el estado de la sequía meteorológica, valores más altos indican condiciones más húmedas o menos severas, mientras que valores más bajos reflejan situaciones de sequía. Por otro lado, la variable Y, valor_pesos, es la variable respuesta y corresponde al Valor Unitario Rural original, expresado en pesos para cada unidad espacial analizada.
El coeficiente de Pearson (r = 0,2009) indica la fuerza y dirección de la relación lineal entre las dos variables. En este caso, el valor positivo muestra que, en promedio, a medida que mejora el PDSI (lo que implica menos sequía), el valor de la tierra tiende a aumentar. Sin embargo, la magnitud cercana a 0,2 sugiere que esta relación es débil, lo que significa que el PDSI explica solo una parte reducida de la variabilidad en el valor del suelo.
El p-value (≈ 0,00) indica que la relación observada es estadísticamente significativa. Esto significa que la probabilidad de obtener este coeficiente por azar es prácticamente nula, lo cual es respaldado por el gran tamaño muestral utilizado en el análisis. En este caso, se trabajó con 100.000 observaciones, lo que aumenta la estabilidad del coeficiente y contribuye a la alta significancia estadística, incluso cuando la relación entre las variables es débil.
La pendiente (β = 498.265,23) corresponde a la pendiente de la recta de ajuste lineal. Este valor sugiere que, en promedio, por cada unidad de aumento del PDSI, el valor unitario rural se incrementa en aproximadamente $498.265, manteniendo constantes todas las demás condiciones.

###### Sperman
"""

from scipy.stats import spearmanr

# =========================
# Formato argentino moneda
# =========================
def fmt_ar(v, dec=2):
    if abs(v) < 0.0000005:
        v = 0
    return f"{v:,.{dec}f}".replace(",", "X").replace(".", ",").replace("X", ".")

def fmt_int_ar(v):
    return f"{v:,}".replace(",", ".")

def fmt_cient_ar(v):
    # Notación científica con coma decimal
    base, exp = f"{v:.2e}".split("e")
    base = base.replace(".", ",")
    return f"{base}e{exp}"

# -----------------------
# 1) Selección y limpieza
# -----------------------
xcol = "PDSI_promedio"
ycol = "valor_pesos"

df_xy = df[[xcol, ycol]].copy()
df_xy[xcol] = pd.to_numeric(df_xy[xcol], errors="coerce")
df_xy[ycol] = pd.to_numeric(df_xy[ycol], errors="coerce")
df_xy = df_xy.dropna()

# Muestreo opcional
n = 100000
if len(df_xy) > n:
    df_xy = df_xy.sample(n=n, random_state=42)

# -----------------------
# 2) Spearman
# -----------------------
rho, p = spearmanr(df_xy[xcol], df_xy[ycol])

# -----------------------
# 3) Tabla de resultados
# -----------------------
tabla_resultados = pd.DataFrame({
    "Variable X": [xcol],
    "Variable Y": [ycol],
    "Coeficiente Spearman (ρ)": [rho],
    "p-value": [p],
    "N observaciones": [len(df_xy)]
})

# -----------------------
# 4) Mostrar tabla formato argentino
# -----------------------
tabla_resultados.style\
    .set_caption("Resultado del análisis de correlación de Spearman")\
    .format({
        "Coeficiente Spearman (ρ)": lambda v: fmt_ar(v, 4),
        "p-value": fmt_cient_ar,
        "N observaciones": fmt_int_ar
    })\
    .set_properties(**{"text-align": "center"})

"""El coeficiente de Spearman obtenido (ρ = −0,0454) muestra que la relación monotónica entre el índice de sequía de Palmer y el valor unitario rural es muy débil, lo que indica que el efecto de la sequía meteorológica no se manifiesta de manera uniforme u ordenada en todas las unidades espaciales. Si bien el resultado es estadísticamente significativo (p ≈ 7,6 × 10⁻⁴⁷; n = 100.000), su baja magnitud sugiere que el impacto del PDSI sobre el valor del suelo no sigue un patrón monotónico simple, sino que se encuentra mediado por condiciones locales, productivas y territoriales.

####3 Modelo Predictivo

El desarrollo del modelo predictivo constituye la etapa en la que los datos históricos se utilizan para estimar el comportamiento futuro del valor de la tierra rural. Este proceso se enmarca dentro del aprendizaje automático, un campo de la inteligencia artificial que permite a los sistemas aprender patrones a partir de datos y mejorar su capacidad de predicción sin necesidad de ser programados explícitamente para cada caso. El aprendizaje automático abarca distintos enfoques, en este estudio se emplea aprendizaje supervisado, ya que el objetivo es predecir el valor unitario rural en pesos a partir de variables explicativas conocidas.  
Para abordar esta tarea se seleccionaron algoritmos como Random Forest y XGBoost, técnicas reconocidas por su robustez, su capacidad para modelar relaciones no lineales y su buen desempeño en problemas de regresión. Estos modelos serán entrenados bajo las mismas condiciones con el objetivo de compararlos posteriormente y determinar cuál ofrece un mejor ajuste para predecir el valor unitario rural.

- XGBoost: es un algoritmo de aprendizaje automático basado en la técnica de gradient boosting, que construye múltiples árboles de decisión de manera secuencial para mejorar progresivamente la capacidad predictiva. Los árboles de decisión son estructuras en forma de diagrama que dividen los datos en ramas según reglas simples, lo que permite tomar decisiones paso a paso hasta llegar a una predicción. Cada nuevo árbol generado por XGBoost se enfoca en corregir los errores cometidos por los anteriores, reforzando aquellas áreas donde el modelo previo mostró mayor dificultad. Gracias a este proceso iterativo, el modelo final logra capturar patrones complejos y no lineales en los datos. Además, XGBoost incorpora optimizaciones internas que reducen el sobreajuste, aceleran el entrenamiento y permiten trabajar de manera eficiente con grandes volúmenes de información, produciendo modelos robustos y de alto rendimiento.
- RandomForest: es un algoritmo de aprendizaje automático que se basa en la construcción simultánea de múltiples árboles de decisión con el objetivo de producir predicciones más estables y precisas. Cada árbol se entrena utilizando una muestra diferente del dataset original y selecciona aleatoriamente un subconjunto de variables en cada división, lo que introduce diversidad entre ellos y evita que el modelo se sobreajuste a patrones específicos del conjunto de entrenamiento. Una vez construidos todos los árboles, el modelo combina sus resultados: en problemas de regresión, como en este caso, promedia las predicciones individuales para obtener un valor final más robusto. Esta estrategia permite capturar relaciones complejas entre las variables y mejorar la capacidad generalizadora del modelo, manteniendo al mismo tiempo una estructura intuitiva basada en decisiones secuenciales.

La variable objetivo seleccionada es el valor unitario rural, lo que permite que los modelos aprendan a estimar su variación a partir de la información climática, espacial y temporal disponible. Con el fin de garantizar una evaluación adecuada del rendimiento y evitar sobreajuste, el dataset se dividió en tres subconjuntos:
-  un 70 % para entrenamiento,
- un 20 % para prueba y
- un 10 % para validación final.

Esta estructura asegura que el desempeño del modelo sea representativo y que su capacidad predictiva se evalúe de manera objetiva y confiable.

Las métricas utilizadas para evaluar el desempeño de los modelos predictivos fueron el RMSE, el MAE, el coeficiente de determinación R² y el error relativo porcentual. El RMSE, o raíz del error cuadrático medio, mide qué tan lejos están, en promedio, las predicciones del modelo respecto de los valores reales y penaliza de manera más intensa los errores grandes al elevarlos al cuadrado antes de promediarlos. El MAE, o error absoluto medio, representa la diferencia promedio en valor absoluto entre lo predicho y lo observado, ofreciendo una medida directa y fácilmente interpretable de la precisión general del modelo sin amplificar de forma exagerada los desvíos más altos. El coeficiente R² indica qué proporción de la variabilidad del valor del suelo es explicada por el modelo, mientras que el error relativo porcentual expresa la magnitud del error en términos porcentuales respecto de los valores reales, permitiendo comparar el rendimiento en unidades homogéneas para el análisis territorial y económico.

#####Division del Dataset

El conjunto de datos fue dividido de manera aleatoria en tres subconjuntos: 70 % para entrenamiento del modelo, 20 % para prueba y 10 % para validación final, garantizando la reproducibilidad del proceso y una evaluación independiente del desempeño predictivo.
"""

from sklearn.model_selection import train_test_split

# -----------------------
# 1) Dataset base
# -----------------------
# Usamos el dataset integrado
df_base = df.copy()

# -----------------------
# 2) Primera división
#    70% train + 30% temporal
# -----------------------
df_train, df_temp = train_test_split(
    df_base,
    test_size=0.30,
    random_state=42,
    shuffle=True
)

# -----------------------
# 3) Segunda división
#    del 30% -> 20% test y 10% validación
# -----------------------
df_test, df_val = train_test_split(
    df_temp,
    test_size=1/3,   # 10% del total
    random_state=42,
    shuffle=True
)

# -----------------------
# 4) Control de tamaños
# -----------------------
print("✔ División del dataset:")
print(f"Entrenamiento: {len(df_train)} filas ({len(df_train)/len(df_base)*100:.1f}%)")
print(f"Prueba:        {len(df_test)} filas ({len(df_test)/len(df_base)*100:.1f}%)")
print(f"Validación:    {len(df_val)} filas ({len(df_val)/len(df_base)*100:.1f}%)")

"""#####Separar X / y (features y target)

Target (y): valor_pesos

Features (X): variables explicativas
"""

# -----------------------
# 1) Definir target y features
# -----------------------
target = "valor_pesos"

features = [
    "anio",
    "PDSI_promedio",
    "IP_prom_area",
    "IP_prom_simple"
]

# Usar solo las features que existan en el dataset
features = [c for c in features if c in df.columns]

# -----------------------
# 2) Separar X / y
# -----------------------
X_train = df_train[features].copy()
y_train = df_train[target].copy()

X_test  = df_test[features].copy()
y_test  = df_test[target].copy()

X_val   = df_val[features].copy()
y_val   = df_val[target].copy()

# -----------------------
# 3) Control rápido
# -----------------------
print("✔ Shapes:")
print("X_train:", X_train.shape, "| y_train:", y_train.shape)
print("X_test: ", X_test.shape,  "| y_test: ", y_test.shape)
print("X_val:  ", X_val.shape,   "| y_val:  ", y_val.shape)

"""El conjunto de datos fue dividido en subconjuntos de entrenamiento, validación y prueba. El conjunto de entrenamiento contiene 150.002 observaciones con 3 variables predictoras, mientras que los conjuntos de validación y prueba contienen 21.429 y 42.858 observaciones respectivamente. La variable objetivo corresponde al valor de la tierra rural.

#####Imputacion y escalado

- Imputación (mediana): Completa valores faltantes usando la mediana de cada variable, evitando sesgos por outliers. Se eligió la mediana como método de imputación en lugar de la media porque resulta más robusta frente a valores extremos y distribuciones asimétricas

- Escalado (StandardScaler): Lleva todas las variables predictoras a una escala comparable (media 0, desvío 1).

Se elimino IP_promedio_ simple
"""

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# -----------------------
# 1) Definir columnas
# -----------------------
target = "valor_pesos"

features = [
    "anio",
    "PDSI_promedio",
    "IP_prom_area",
]

# Usar solo las columnas que existan
features = [c for c in features if c in X_train.columns]

# -----------------------
# 2) Pipeline de preprocesamiento
# -----------------------
preprocessor = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),   # imputación robusta
    ("scaler", StandardScaler())                      # escalado
])

# -----------------------
# 3) Ajustar SOLO con entrenamiento
# -----------------------
X_train_prep = preprocessor.fit_transform(X_train[features])

# -----------------------
# 4) Transformar test y validación
# -----------------------
X_test_prep = preprocessor.transform(X_test[features])
X_val_prep  = preprocessor.transform(X_val[features])

# -----------------------
# 5) Control de shapes
# -----------------------
print("✔ Shapes luego del preprocesamiento:")
print("X_train_prep:", X_train_prep.shape)
print("X_test_prep: ", X_test_prep.shape)
print("X_val_prep:  ", X_val_prep.shape)

"""#####Modelo Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# =========================
# Formato argentino
# =========================
def fmt_ar(v):
    if abs(v) < 0.005:  # evita -0,00
        v = 0
    return f"{v:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def fmt_r2(v):
    return f"{v:.4f}".replace(".", ",")

# -----------------------
# 1) Definir modelo
# -----------------------
rf_model = RandomForestRegressor(
    n_estimators=250,
    max_depth=None,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

# -----------------------
# 2) Entrenar
# -----------------------
rf_model.fit(X_train_prep, y_train)

# -----------------------
# 3) Predicciones
# -----------------------
y_pred_train = rf_model.predict(X_train_prep)
y_pred_test  = rf_model.predict(X_test_prep)
y_pred_val   = rf_model.predict(X_val_prep)

# -----------------------
# 4) Métricas
# -----------------------
def metricas(y_true, y_pred, nombre):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae  = mean_absolute_error(y_true, y_pred)
    r2   = r2_score(y_true, y_pred)

    print(f"\n{nombre}")
    print(f"RMSE: {fmt_ar(rmse)}")
    print(f"MAE : {fmt_ar(mae)}")
    print(f"R²  : {fmt_r2(r2)}")

metricas(y_train, y_pred_train, "Entrenamiento")
metricas(y_test,  y_pred_test,  "Prueba")
metricas(y_val,   y_pred_val,   "Validación final")

"""Grafico"""

from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

# Calcular R² sobre validación final
r2_val = r2_score(y_val, y_pred_val)

plt.figure(figsize=(6, 6))

plt.scatter(
    y_val,              # Observado
    y_pred_val,         # Predicho
    s=10,
    alpha=0.35,
    color="#7A3DB8",    # violeta
    label="Valor predicho"
)

# Línea ideal (y = x)
lim_min = min(y_val.min(), y_pred_val.min())
lim_max = max(y_val.max(), y_pred_val.max())

plt.plot(
    [lim_min, lim_max],
    [lim_min, lim_max],
    linestyle="--",
    color="#5BC0EB",    # celeste
    linewidth=2,
    label="Ajuste ideal (observado = predicho)"
)

# Texto con R² dentro del gráfico
plt.text(
    0.05, 0.95,
    f"$R^2 = {r2_val:.3f}$",
    transform=plt.gca().transAxes,
    fontsize=12,
    verticalalignment="top",
    bbox=dict(boxstyle="round", facecolor="white", alpha=0.8)
)

plt.xlabel("Valor observado (pesos)")
plt.ylabel("Valor predicho (pesos)")
plt.title("Valores observados vs predichos\nConjunto de validación final")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""#####XGBoost"""

from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# =========================
# Formato argentino
# =========================
def fmt_ar(v):
    if abs(v) < 0.005:  # evita -0,00
        v = 0
    return f"{v:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def fmt_r2(v):
    return f"{v:.4f}".replace(".", ",")

# -----------------------
# 1) Definir modelo
# -----------------------
xgb_model = XGBRegressor(
    n_estimators=250,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

# -----------------------
# 2) Entrenar
# -----------------------
xgb_model.fit(X_train_prep, y_train)

# -----------------------
# 3) Predicciones
# -----------------------
y_pred_train_xgb = xgb_model.predict(X_train_prep)
y_pred_test_xgb  = xgb_model.predict(X_test_prep)
y_pred_val_xgb   = xgb_model.predict(X_val_prep)

# -----------------------
# 4) Métricas
# -----------------------
def metricas(y_true, y_pred, nombre):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae  = mean_absolute_error(y_true, y_pred)
    r2   = r2_score(y_true, y_pred)

    print(f"\n{nombre}")
    print(f"RMSE: {fmt_ar(rmse)}")
    print(f"MAE : {fmt_ar(mae)}")
    print(f"R²  : {fmt_r2(r2)}")

metricas(y_train, y_pred_train_xgb, "Entrenamiento")
metricas(y_test,  y_pred_test_xgb,  "Prueba")
metricas(y_val,   y_pred_val_xgb,   "Validación final")

"""Grafico"""

import matplotlib.pyplot as plt

# -----------------------
# Predicción vs Observado
# -----------------------
plt.figure(figsize=(6, 6))

plt.scatter(
    y_val,              # Observado
    y_pred_val_xgb,     # Predicho
    s=10,
    alpha=0.35,
    color="#2E8B57",    # Verde
    label="Valor predicho"
)

# Línea ideal (y = x)
lim_min = min(y_val.min(), y_pred_val_xgb.min())
lim_max = max(y_val.max(), y_pred_val_xgb.max())

plt.plot(
    [lim_min, lim_max],
    [lim_min, lim_max],
    linestyle="--",
    color="#5BC0EB",    # Celeste
    linewidth=2,
    label="Ajuste ideal (observado = predicho)"
)

# Título y etiquetas
plt.xlabel("Valor observado (pesos)")
plt.ylabel("Valor predicho (pesos)")
plt.title("Valores observados vs predichos\nConjunto de validación final")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""Tabla comparativa de Modelos"""

# =========================
# Función métricas
# =========================
def calc_metricas(y_true, y_pred):
    return {
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
        "MAE": mean_absolute_error(y_true, y_pred),
        "R²": r2_score(y_true, y_pred)
    }

# =========================
# Formato argentino
# =========================
def fmt_ar(v):
    if abs(v) < 0.005:  # evita -0,00
        v = 0
    return f"{v:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

# =========================
# Calcular métricas
# =========================
resultados = []

# Random Forest
for nombre_set, y_true, y_pred in [
    ("Entrenamiento", y_train, y_pred_train),
    ("Prueba", y_test, y_pred_test),
    ("Validación final", y_val, y_pred_val)
]:
    m = calc_metricas(y_true, y_pred)
    resultados.append([
        "Random Forest",
        nombre_set,
        m["RMSE"],
        m["MAE"],
        m["R²"]
    ])

# XGBoost
for nombre_set, y_true, y_pred in [
    ("Entrenamiento", y_train, y_pred_train_xgb),
    ("Prueba", y_test, y_pred_test_xgb),
    ("Validación final", y_val, y_pred_val_xgb)
]:
    m = calc_metricas(y_true, y_pred)
    resultados.append([
        "XGBoost",
        nombre_set,
        m["RMSE"],
        m["MAE"],
        m["R²"]
    ])

# =========================
# Tabla final
# =========================
tabla_comparacion = pd.DataFrame(
    resultados,
    columns=["Modelo", "Conjunto", "RMSE", "MAE", "R²"]
)

tabla_comparacion.style\
    .set_caption("Comparación de desempeño entre Random Forest y XGBoost")\
    .format({
        "RMSE": fmt_ar,
        "MAE": fmt_ar,
        "R²": "{:.4f}"
    })\
    .set_properties(**{"text-align": "center"})

# Ver que las predicciones NO son idénticas punto a punto
np.allclose(y_pred_val, y_pred_val_xgb)

np.mean(np.abs(y_pred_val - y_pred_val_xgb))

"""###Eleccion del modelo y prueba

Los resultados obtenidos muestran que ambos modelos presentan un desempeño prácticamente idéntico en los conjuntos de entrenamiento, validación y prueba, con valores de R² cercanos a 0,86. Esto indica una alta capacidad explicativa del modelo respecto al valor de la tierra rural. Asimismo, no se evidencian problemas de sobreajuste, dado que las métricas se mantienen estables entre los distintos conjuntos de datos. En este contexto, se selecciona el modelo Random Forest debido a su menor complejidad computacional y mayor interpretabilidad, sin pérdida de precisión respecto a XGBoost.

####simulación

¿Qué habría ocurrido con el valor del suelo si las condiciones de sequía hubieran sido distintas, manteniendo constantes el resto de los factores?

Para ello, se utiliza el modelo de predicción previamente entrenado y se parte del conjunto de datos de prueba, que contiene observaciones reales. En una primera instancia, el modelo estima el valor de de la tierra bajo las condiciones efectivamente observadas, es decir, considerando los valores reales de las variables explicativas. Estas predicciones conforman el escenario denominado “Real”.

Luego, se construye un segundo escenario hipotético o contrafáctico a partir de las mismas observaciones, pero modificando únicamente la variable PDSI_promedio, a la que se le asigna un valor de -4 para representar una situación de sequía extrema. De este modo, el año y el índice de productividad del suelo permanecen constantes, lo que permite aislar el efecto específico de la sequía sobre el valor estimado de la tierra. Sobre estas nuevas condiciones, el modelo vuelve a generar predicciones, que se almacenan en un segundo conjunto identificado como “Sequia_Extrema”.

La comparación entre ambos escenarios permite medir cuánto cambiaría el valor del suelo si la intensidad de la sequía hubiese sido distinta, sin alterar los demás factores. En decir, la diferencia entre el valor predicho en el escenario real y el valor predicho en el escenario de sequía extrema representa el impacto atribuible exclusivamente a la variación en las condiciones hídricas. Si la reducción estimada del valor es importante, ello indica una mayor sensibilidad del territorio frente a eventos de sequía; si la variación es reducida, sugiere una menor dependencia de esa variable climática.
"""

# ==========================
# 1) Escenario REAL
# ==========================
X_real = X_test.copy()
X_real_prep = preprocessor.transform(X_real)

df_real = X_real.copy()
df_real["Escenario"] = "Real"
df_real["valor_predicho"] = rf_model.predict(X_real_prep)

# ==========================
# 2) Escenario SEQUÍA EXTREMA
# ==========================
X_extrema = X_test.copy()
X_extrema["PDSI_promedio"] = -4

X_extrema_prep = preprocessor.transform(X_extrema)

df_extrema = X_extrema.copy()
df_extrema["Escenario"] = "Sequia_Extrema"
df_extrema["valor_predicho"] = rf_model.predict(X_extrema_prep)

# ==========================
# 3) Unir
# ==========================
df_escenarios = pd.concat([df_real, df_extrema], ignore_index=True)

print("✅ df_escenarios creado:", df_escenarios.shape)

# ================= Parámetros =================
pedanias_interes = ["ASCASUBI", "BALLESTEROS", "BELL VILLE", "LITIN", "LOBOY"]

def normalizar_txt(s):
    if pd.isna(s):
        return ""
    s = str(s).upper().strip()
    s = unicodedata.normalize("NFD", s).encode("ascii", "ignore").decode("utf-8")
    s = s.replace("  ", " ")
    return s

# --- Semáforo ---
def clasificar_semaforo(x):
    # x en %
    if x <= -3.5:
        return "🔴 Alto (≤ -3,5%)"
    elif x <= -2:
        return "🟡 Moderado (-3,5% a -2%)"
    elif x <= -0.5:
        return "🟢 Bajo (-2% a -0,5%)"
    else:
        return "🔵 Leve (> -0,5%)"

colores = {
    "🔴 Alto (≤ -3,5%)": "#c92a2a",
    "🟡 Moderado (-3,5% a -2%)": "#f08c00",
    "🟢 Bajo (-2% a -0,5%)": "#2f9e44",
    "🔵 Leve (> -0,5%)": "#1c7ed6",
}

# ================= Formato argentino =================
def fmt_ar_pct(v, dec=2):
    if pd.isna(v):
        v = 0.0
    # evita -0,00
    if abs(v) < 0.5 * 10**(-dec):
        v = 0.0
    return f"{v:,.{dec}f}".replace(",", "X").replace(".", ",").replace("X", ".") + "%"

# ================= Centrar mapa =================
depto_union_5346 = union.to_crs(5346)
centro = depto_union_5346.geometry.centroid.iloc[0]
centro = gpd.GeoSeries([centro], crs=5346).to_crs(4326).iloc[0]

m = folium.Map(
    location=[centro.y, centro.x],
    zoom_start=9,
    tiles=None,
    control_scale=True
)

# ======== Mapas base ========
folium.TileLayer("OpenStreetMap", name="OpenStreetMap").add_to(m)
folium.TileLayer(
    tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    attr="Esri",
    name="Esri Satellite",
    overlay=False,
    control=True
).add_to(m)

# ================= Helper para agregar capas =================
def add_gdf_layer(
    gdf, name, color, weight=2, fill=False, fill_opacity=0.3,
    tooltip_fields=None, popup_fields=None
):
    if gdf is None or gdf.empty:
        return

    gdf_clean = gdf[gdf.geometry.type.isin(
        ["LineString", "MultiLineString", "Polygon", "MultiPolygon"]
    )].explode(index_parts=False).reset_index(drop=True)

    if gdf_clean.empty:
        return

    folium.GeoJson(
        gdf_clean.to_crs(4326),
        name=name,
        style_function=lambda x: {
            "color": color,
            "weight": weight,
            "fillOpacity": fill_opacity if fill else 0,
        },
        tooltip=folium.GeoJsonTooltip(fields=tooltip_fields) if tooltip_fields else None,
        popup=folium.GeoJsonPopup(fields=popup_fields) if popup_fields else None
    ).add_to(m)

# ============================================================
# ORDEN PEDIDO:
# 1) Departamento
# 2) Semáforo
# 3) Red vial + Hidrología
# ============================================================

# ================= 1) Departamento =================
add_gdf_layer(depto_union_5346, "Departamento UNIÓN", "black", weight=3)

# ================= 2) SEMÁFORO (arriba del depto) =================
# 2.1 Impacto por observación (Real vs Sequía Extrema)
real = df_escenarios[df_escenarios["Escenario"] == "Real"]["valor_predicho"].to_numpy()
extrema = df_escenarios[df_escenarios["Escenario"] == "Sequia_Extrema"]["valor_predicho"].to_numpy()

real = np.where(np.abs(real) < 1e-9, np.nan, real)
impacto_pct = ((extrema - real) / real) * 100
impacto_pct = np.nan_to_num(impacto_pct, nan=0.0, posinf=0.0, neginf=0.0)

# pedanía alineada con X_test
df_base_test = df.loc[X_test.index].copy()
df_imp = pd.DataFrame({
    "Pedania": df_base_test["Pedania"].astype(str),
    "impacto_pct": impacto_pct
})
df_imp["Pedania_norm"] = df_imp["Pedania"].apply(normalizar_txt)

# 2.2 Promedio por pedanía
impacto_ped = (
    df_imp.groupby("Pedania_norm")["impacto_pct"]
          .mean()
          .reset_index()
)
impacto_ped["Categoria"] = impacto_ped["impacto_pct"].apply(clasificar_semaforo)

# 2.3 Unir a geometría de pedanías (solo interés)
ped = pedanias_union.copy()
ped["Pedania_norm"] = ped["nombre"].apply(normalizar_txt)

interes_norm = set(normalizar_txt(x) for x in pedanias_interes)
ped = ped[ped["Pedania_norm"].isin(interes_norm)].copy()

ped = ped.merge(impacto_ped, on="Pedania_norm", how="left")
ped["impacto_pct"] = ped["impacto_pct"].fillna(0.0)
ped["Categoria"] = ped["Categoria"].fillna("🔵 Leve (> -0,5%)")
ped["impacto_pct_txt"] = ped["impacto_pct"].map(lambda v: fmt_ar_pct(v, 2))

# 2.4 Dibujar semáforo
for cat, color in colores.items():
    sub = ped[ped["Categoria"] == cat].copy()
    if sub.empty:
        continue

    folium.GeoJson(
        sub.to_crs(4326),
        name=f"Semáforo — {cat}",
        style_function=lambda feat, c=color: {
            "color": "black",
            "weight": 2,
            "fillColor": c,
            "fillOpacity": 0.35
        },
        tooltip=folium.GeoJsonTooltip(
            fields=["nombre", "impacto_pct_txt", "Categoria"],
            aliases=["Pedanía", "Cambio promedio (%)", "Clasificación"]
        ),
        popup=folium.GeoJsonPopup(
            fields=["nombre", "impacto_pct_txt", "Categoria"],
            aliases=["Pedanía", "Cambio promedio (%)", "Clasificación"]
        )
    ).add_to(m)

# ================= 3) Red vial + Hidrología (arriba) =================
# Red vial
add_gdf_layer(nacional_union,   "Red vial nacional", "black", weight=3)
add_gdf_layer(provincial_union, "Red vial provincial", "gray",  weight=2)
add_gdf_layer(regional_union,   "Red vial regional", "brown", weight=2)

# Hidrología / infraestructura hídrica
add_gdf_layer(gdf_cursos,     "Cursos de agua", "blue", weight=2)
add_gdf_layer(gdf_acueductos, "Acueductos", "purple", weight=2)
add_gdf_layer(gdf_embalses,   "Embalses", "lightblue", weight=2, fill=True, fill_opacity=0.35)
add_gdf_layer(gdf_cuerpos,    "Cuerpos de Agua Naturales", "aqua", weight=2, fill=True, fill_opacity=0.35)

# Radios urbanos
if "radios_urbanos" in globals():
    radios_union = radios_urbanos.to_crs(5346)
    try:
        gdf_radios_urbanos = gpd.clip(radios_union, depto_union_5346)
    except Exception:
        gdf_radios_urbanos = gpd.sjoin(
            radios_union, depto_union_5346[["geometry"]],
            how="inner", predicate="intersects"
        ).drop(columns="index_right")

    if gdf_radios_urbanos is not None and (not gdf_radios_urbanos.empty):
        add_gdf_layer(
            gdf_radios_urbanos, "Radios urbanos", "red",
            weight=2, fill=True, fill_opacity=0.10,
            tooltip_fields=["nombre"] if "nombre" in gdf_radios_urbanos.columns else None,
            popup_fields=["nombre"] if "nombre" in gdf_radios_urbanos.columns else None
        )

# ================= Control de capas =================
folium.LayerControl(collapsed=False, position="bottomright").add_to(m)

# ================= Título =================
title_html = """
<h3 align="center" style="font-size:20px; margin-top: 10px;">
¿Qué habría ocurrido con el valor del suelo si la sequía hubiese sido distinta?<br>
<span style="font-size:14px;">
Simulación contrafáctica: PDSI_promedio = -4 (sequía extrema), manteniendo constantes anio e IP_prom_area
</span>
</h3>
"""
m.get_root().html.add_child(folium.Element(title_html))

# ================= LEYENDA UNIFICADA =================
legend_unificada = """
<div style="
    position: fixed;
    bottom: 30px; left: 30px;
    border:2px solid grey;
    z-index:9999;
    font-size:13px;
    background-color:white;
    padding: 10px;
    border-radius:6px;
    box-shadow: 2px 2px 6px rgba(0,0,0,0.3);
">

<b>Leyenda</b><br><br>

<b>Semáforo de impacto</b><br>
<span style="color:#c92a2a;">&#9632;</span> 🔴 Alto (≤ -3,5%)<br>
<span style="color:#f08c00;">&#9632;</span> 🟡 Moderado (-3,5% a -2%)<br>
<span style="color:#2f9e44;">&#9632;</span> 🟢 Bajo (-2% a -0,5%)<br>
<span style="color:#1c7ed6;">&#9632;</span> 🔵 Leve (> -0,5%)<br>

<hr style="margin:6px 0;">

<b>Capas</b><br>
<span style="color:black;">&#8212;&#8212;</span> Red vial nacional<br>
<span style="color:gray;">&#8212;&#8212;</span> Red vial provincial<br>
<span style="color:brown;">&#8212;&#8212;</span> Red vial regional<br>
<span style="color:blue;">&#8212;&#8212;</span> Cursos de agua<br>
<span style="color:purple;">&#8212;&#8212;</span> Acueductos<br>
<span style="color:deepskyblue;">&#9632;</span> Embalses<br>
<span style="color:aqua;">&#9632;</span> Cuerpos de agua naturales<br>
<span style="color:red;">&#9632;</span> Radios urbanos<br>

</div>
"""

m.get_root().html.add_child(folium.Element(legend_unificada))

# ================= Flecha Norte =================
north_html = """
<div style="
    position: fixed;
    top: 70px; right: 50px;
    z-index:9999;
    text-align:center;
    background-color: rgba(255,255,255,0.8);
    padding: 6px;
    border:1px solid #666;
    border-radius: 6px;
    font-size: 14px;
">
<b>N</b><br>
<span style="font-size:22px;">↑</span>
</div>
"""
m.get_root().html.add_child(folium.Element(north_html))

m

"""El mapa representa el efecto estimado que habría tenido una sequía extrema sobre el valor del suelo en cada pedanía analizada, a partir de una simulación contrafáctica que compara las predicciones del modelo bajo condiciones reales con aquellas obtenidas al imponer un escenario de sequía severa (PDSI_promedio = -4), manteniendo constantes el año y el índice de productividad del suelo. De este modo, la diferencia entre ambos escenarios puede interpretarse como el impacto atribuible exclusivamente a la variación en las condiciones de sequía.

Los resultados se expresan como el cambio porcentual promedio del valor del suelo en cada pedanía y se representan mediante una escala de colores tipo “semáforo”, que permite visualizar la magnitud del impacto y la sensibilidad territorial frente a la sequía. En términos generales, se observa que todas las jurisdicciones analizadas experimentarían una disminución del valor del suelo bajo el escenario extremo, aunque con distinta intensidad, predominando impactos de carácter moderado y registrándose en algunos casos caídas más pronunciadas. No se identifican situaciones de estabilidad ni incrementos del valor.

En esta representación, el color rojo indica un impacto alto, asociado a reducciones iguales o superiores al 3,5%, lo que evidencia una elevada sensibilidad a la sequía. El color amarillo representa un impacto moderado, con disminuciones entre el 3,5% y el 2%, mientras que el color verde señala un impacto bajo, con caídas entre el 2% y el 0,5%. Finalmente, el color azul corresponde a un impacto leve, con variaciones menores al 0,5%, lo que indica una relativa estabilidad frente a cambios en las condiciones hídricas.

#####Mapa con cambio de PDSI manual entre -4 y 4

- Configuración de interfaz interactiva (ipywidgets)
"""

!pip -q install ipywidgets

"""- Librerias extras"""

import ipywidgets as widgets
from IPython.display import display, clear_output

#Slider que actualiza el mapa al cambiar PDSI

# ================= Parámetros =================
pedanias_interes = ["ASCASUBI", "BALLESTEROS", "BELL VILLE", "LITIN", "LOBOY"]

def normalizar_txt(s):
    if pd.isna(s):
        return ""
    s = str(s).upper().strip()
    s = unicodedata.normalize("NFD", s).encode("ascii", "ignore").decode("utf-8")
    return s

# Umbrales estrictos
def clasificar_semaforo(x):
    if x <= -3.5:
        return "🔴 Alto (≤ -3,5%)"
    elif x <= -2:
        return "🟡 Moderado (-3,5% a -2%)"
    elif x <= -0.5:
        return "🟢 Bajo (-2% a -0,5%)"
    else:
        return "🔵 Leve (> -0,5%)"

colores = {
    "🔴 Alto (≤ -3,5%)": "#c92a2a",
    "🟡 Moderado (-3,5% a -2%)": "#f08c00",
    "🟢 Bajo (-2% a -0,5%)": "#2f9e44",
    "🔵 Leve (> -0,5%)": "#1c7ed6",
}

# ================= Formato argentino =================
def fmt_ar_num(v, dec=2):
    if pd.isna(v):
        v = 0.0
    # evita -0,00
    if abs(v) < 0.5 * 10**(-dec):
        v = 0.0
    return f"{v:,.{dec}f}".replace(",", "X").replace(".", ",").replace("X", ".")

def fmt_ar_pct(v, dec=2):
    return fmt_ar_num(v, dec=dec) + "%"

# ================= Modelo =================
modelo_final = rf_model  # o xgb_model si querés

# ================= Cache: predicción real (una sola vez) =================
X_test_prep = preprocessor.transform(X_test)
pred_real = modelo_final.predict(X_test_prep)

# Pedanía alineada a X_test (para agregar por pedanía)
df_base_test = df.loc[X_test.index].copy()
df_base_test["Pedania_norm"] = df_base_test["Pedania"].apply(normalizar_txt)

# Preparar pedanías_union SOLO interés
ped = pedanias_union.copy()
ped["Pedania_norm"] = ped["nombre"].apply(normalizar_txt)
interes_norm = set(normalizar_txt(x) for x in pedanias_interes)
ped = ped[ped["Pedania_norm"].isin(interes_norm)].copy()

# ================= Helper para agregar capas =================
def add_gdf_layer(
    m, gdf, name, color, weight=2, fill=False, fill_opacity=0.3,
    tooltip_fields=None, popup_fields=None, layer_obj=None, fillColor=None
):
    if gdf is None or gdf.empty:
        return

    gdf_clean = gdf[gdf.geometry.type.isin(
        ["LineString", "MultiLineString", "Polygon", "MultiPolygon"]
    )].explode(index_parts=False).reset_index(drop=True)

    if gdf_clean.empty:
        return

    style_fn = (lambda feat: {
        "color": color,
        "weight": weight,
        "fillColor": fillColor if fillColor else color,
        "fillOpacity": fill_opacity if fill else 0
    })

    gj = folium.GeoJson(
        gdf_clean.to_crs(4326),
        name=name,
        style_function=style_fn,
        tooltip=folium.GeoJsonTooltip(fields=tooltip_fields, aliases=tooltip_fields) if tooltip_fields else None,
        popup=folium.GeoJsonPopup(fields=popup_fields, aliases=popup_fields) if popup_fields else None,
    )

    if layer_obj is None:
        gj.add_to(m)
    else:
        gj.add_to(layer_obj)

# ================= Función mapa para PDSI elegido =================
def construir_mapa(pdsi_val):
    # 1) Contrafáctico: cambiar SOLO PDSI
    X_cf = X_test.copy()
    X_cf["PDSI_promedio"] = pdsi_val
    X_cf_prep = preprocessor.transform(X_cf)
    pred_cf = modelo_final.predict(X_cf_prep)

    # 2) Impacto porcentual por observación
    den = np.where(np.abs(pred_real) < 1e-9, np.nan, pred_real)
    impacto_pct = ((pred_cf - pred_real) / den) * 100
    impacto_pct = np.nan_to_num(impacto_pct, nan=0.0, posinf=0.0, neginf=0.0)

    # 3) Promedio por pedanía
    df_imp = pd.DataFrame({
        "Pedania_norm": df_base_test["Pedania_norm"].to_numpy(),
        "impacto_pct": impacto_pct
    })

    impacto_ped = (df_imp.groupby("Pedania_norm")["impacto_pct"]
                        .mean()
                        .reset_index())

    impacto_ped["Categoria"] = impacto_ped["impacto_pct"].apply(clasificar_semaforo)
    impacto_ped["impacto_pct_txt"] = impacto_ped["impacto_pct"].map(lambda v: fmt_ar_pct(v, 2))

    # 4) Unir a pedanías de interés
    g = ped.merge(impacto_ped, on="Pedania_norm", how="left")
    g["impacto_pct"] = g["impacto_pct"].fillna(0.0)
    g["impacto_pct_txt"] = g["impacto_pct_txt"].fillna(fmt_ar_pct(0.0, 2))
    g["Categoria"] = g["Categoria"].fillna("🔵 Leve (> -0,5%)")

    # 5) Mapa base
    depto_union_5346 = union.to_crs(5346)
    centro = depto_union_5346.geometry.centroid.iloc[0]
    centro = gpd.GeoSeries([centro], crs=5346).to_crs(4326).iloc[0]

    m = folium.Map(location=[centro.y, centro.x], zoom_start=9, tiles=None, control_scale=True)

    folium.TileLayer("OpenStreetMap", name="OpenStreetMap").add_to(m)
    folium.TileLayer(
        tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        attr="Esri",
        name="Esri Satellite",
        overlay=False,
        control=True
    ).add_to(m)

    # ============================================================
    # ORDEN: Departamento → Semáforo → Red vial/Hidrología
    # ============================================================

    # A) Departamento
    add_gdf_layer(m, depto_union_5346, "Departamento UNIÓN", "black", weight=3)

    # B) Semáforo (capas tildables por categoría)
    for cat, color in colores.items():
        fg = folium.FeatureGroup(name=f"Semáforo — {cat}", show=True)
        sub = g[g["Categoria"] == cat].copy()
        if sub.empty:
            continue

        add_gdf_layer(
            m, sub, name=cat, color="black", weight=2,
            fill=True,
            fill_opacity=0.35,  # clave para no tapar rutas/ríos
            tooltip_fields=["nombre", "impacto_pct_txt", "Categoria"],
            popup_fields=["nombre", "impacto_pct_txt", "Categoria"],
            layer_obj=fg,
            fillColor=color
        )
        fg.add_to(m)

    # C) Red vial + Hidrología (arriba para que se vea)
    # (Si alguna variable no existe en tu notebook, comentá su línea)
    if "nacional_union" in globals():
        add_gdf_layer(m, nacional_union, "Red vial nacional", "black", weight=3)
    if "provincial_union" in globals():
        add_gdf_layer(m, provincial_union, "Red vial provincial", "gray", weight=2)
    if "regional_union" in globals():
        add_gdf_layer(m, regional_union, "Red vial regional", "brown", weight=2)

    if "gdf_cursos" in globals():
        add_gdf_layer(m, gdf_cursos, "Cursos de agua", "blue", weight=2)
    if "gdf_canales" in globals():
        add_gdf_layer(m, gdf_canales, "Canales de riego", "cyan", weight=2)
    if "gdf_acueductos" in globals():
        add_gdf_layer(m, gdf_acueductos, "Acueductos", "purple", weight=2)
    if "gdf_embalses" in globals():
        add_gdf_layer(m, gdf_embalses, "Embalses", "lightblue", weight=2, fill=True, fill_opacity=0.35)
    if "gdf_cuerpos" in globals():
        add_gdf_layer(m, gdf_cuerpos, "Cuerpos de Agua Naturales", "aqua", weight=2, fill=True, fill_opacity=0.35)

    # Radios urbanos (si existe)
    if "radios_urbanos" in globals():
        radios_union = radios_urbanos.to_crs(5346)
        try:
            gdf_radios_urbanos = gpd.clip(radios_union, depto_union_5346)
        except Exception:
            gdf_radios_urbanos = gpd.sjoin(
                radios_union, depto_union_5346[["geometry"]],
                how="inner", predicate="intersects"
            ).drop(columns="index_right")

        if gdf_radios_urbanos is not None and (not gdf_radios_urbanos.empty):
            add_gdf_layer(
                m, gdf_radios_urbanos, "Radios urbanos", "red",
                weight=2, fill=True, fill_opacity=0.10,
                tooltip_fields=["nombre"] if "nombre" in gdf_radios_urbanos.columns else None,
                popup_fields=["nombre"] if "nombre" in gdf_radios_urbanos.columns else None
            )

    # Control de capas
    folium.LayerControl(collapsed=False, position="bottomright").add_to(m)

    # Título
    title_html = f"""
    <h3 align="center" style="font-size:20px; margin-top: 10px;">
    ¿Qué habría ocurrido con el valor del suelo si la sequía hubiese sido distinta?<br>
    <span style="font-size:14px;">
    Simulación contrafáctica: PDSI_promedio = {pdsi_val:.1f}, manteniendo constantes anio e IP_prom_area
    </span>
    </h3>
    """
    m.get_root().html.add_child(folium.Element(title_html))

    # ================= LEYENDA UNIFICADA =================
    legend_unificada = """
    <div style="
        position: fixed;
        bottom: 30px; left: 30px;
        border:2px solid grey;
        z-index:9999;
        font-size:13px;
        background-color:white;
        padding: 10px;
        border-radius:6px;
        box-shadow: 2px 2px 6px rgba(0,0,0,0.3);
    ">
    <b>Leyenda</b><br><br>

    <b>Semáforo de impacto</b><br>
    <span style="color:#c92a2a;">&#9632;</span> 🔴 Alto (≤ -3,5%)<br>
    <span style="color:#f08c00;">&#9632;</span> 🟡 Moderado (-3,5% a -2%)<br>
    <span style="color:#2f9e44;">&#9632;</span> 🟢 Bajo (-2% a -0,5%)<br>
    <span style="color:#1c7ed6;">&#9632;</span> 🔵 Leve (> -0,5%)<br>

    <hr style="margin:6px 0;">

    <b>Capas</b><br>
    <span style="color:black;">&#8212;&#8212;</span> Red vial nacional<br>
    <span style="color:gray;">&#8212;&#8212;</span> Red vial provincial<br>
    <span style="color:brown;">&#8212;&#8212;</span> Red vial regional<br>
    <span style="color:blue;">&#8212;&#8212;</span> Cursos de agua<br>
    <span style="color:cyan;">&#8212;&#8212;</span> Canales de riego<br>
    <span style="color:purple;">&#8212;&#8212;</span> Acueductos<br>
    <span style="color:deepskyblue;">&#9632;</span> Embalses<br>
    <span style="color:aqua;">&#9632;</span> Cuerpos de agua naturales<br>
    <span style="color:red;">&#9632;</span> Radios urbanos<br>
    </div>
    """
    m.get_root().html.add_child(folium.Element(legend_unificada))

    # Norte
    north_html = """
    <div style="
        position: fixed;
        top: 70px; right: 50px;
        z-index:9999;
        text-align:center;
        background-color: rgba(255,255,255,0.8);
        padding: 6px;
        border:1px solid #666;
        border-radius: 6px;
        font-size: 14px;
    ">
    <b>N</b><br>
    <span style="font-size:22px;">↑</span>
    </div>
    """
    m.get_root().html.add_child(folium.Element(north_html))

    return m

# ================= UI =================
out = widgets.Output()

pdsi_input = widgets.FloatText(
    value=-4.0,
    description="PDSI:",
    style={'description_width': '60px'},
    layout=widgets.Layout(width='200px')
)

aclaracion = widgets.HTML(
    "<span style='font-size:13px; color:gray;'>Ingrese un valor entre -4 (sequía extrema) y 4 (muy húmedo)</span>"
)

def on_change(change):
    valor = change["new"]

    if valor < -4 or valor > 4:
        with out:
            clear_output(wait=True)
            print("⚠️ El PDSI debe estar entre -4 y 4")
        return

    with out:
        clear_output(wait=True)
        display(construir_mapa(valor))

pdsi_input.observe(on_change, names="value")

display(pdsi_input)
display(aclaracion)
display(out)

with out:
    display(construir_mapa(pdsi_input.value))

"""#####Mapa interactivo de sensibilidad del Valor Unitario Rural ante variaciones del índice de sequía (PDSI)

El código implementa una simulación contrafáctica orientada a medir la sensibilidad del valor unitario rural (VUR) frente a cambios en la severidad de la sequía, representada por el índice PDSI. Para ello, utiliza un modelo predictivo ya entrenado y lo aplica sobre el mismo conjunto de observaciones de prueba, de manera que las características estructurales de cada registro (por ejemplo, año e índice de productividad del suelo) se mantienen constantes. La lógica central consiste en modificar únicamente el valor de PDSI de forma controlada, lo que permite atribuir las variaciones en el VUR predicho exclusivamente al cambio en las condiciones de sequía.

En términos operativos, el usuario introduce manualmente dos valores: un PDSI de referencia y un PDSI alternativo. Con esos dos valores, el código genera dos escenarios para cada observación del conjunto de prueba: uno asociado al estado base y otro al estado modificado. Ambos escenarios se transforman con el mismo preprocesamiento utilizado durante el entrenamiento, garantizando consistencia metodológica, y luego el modelo produce una predicción de VUR para cada caso. La diferencia entre ambas predicciones constituye el cambio estimado del VUR ante la variación en la sequía. Además, el código normaliza esa diferencia por el tamaño del cambio en PDSI, obteniendo una medida interpretable como sensibilidad marginal: el cambio esperado en el VUR por cada unidad de variación del PDSI.

Para trasladar el análisis a una escala territorial, el resultado individual se vincula con la pedanía correspondiente a cada observación mediante la alineación por índices con el dataset original. A continuación, las diferencias se agregan por pedanía calculando un promedio, lo que produce un indicador sintético que resume, para cada jurisdicción, el impacto esperado del cambio de sequía sobre el VUR. Esta agregación permite comparar pedanías entre sí e identificar cuáles muestran mayor vulnerabilidad o sensibilidad ante un empeoramiento de las condiciones climáticas.
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

# =========================================================
# MAPA: Sensibilidad del VUR al cambio en PDSI
# - Orden de dibujo: Departamento -> Semáforo -> Red vial/Hidrología/Radios (arriba)
# - Clasificación por SIGNO y MAGNITUD de ΔVUR (nuevo - base):
#     rojo/amarillo/verde = pérdida (ΔVUR < 0)
#     azul = neutra/mejora (ΔVUR >= 0)
# =========================================================

# ================= Parámetros =================
pedanias_interes = ["ASCASUBI", "BALLESTEROS", "BELL VILLE", "LITIN", "LOBOY"]

def normalizar_txt(s):
    if pd.isna(s):
        return ""
    s = str(s).upper().strip()
    s = unicodedata.normalize("NFD", s).encode("ascii", "ignore").decode("utf-8")
    s = s.replace("  ", " ")
    return s

# ================= Formato argentino =================
def fmt_ar(v, sufijo=""):
    if pd.isna(v):
        v = 0.0
    # evita -0,00 / -0,01 por ruido numérico
    if abs(v) < 0.005:
        v = 0.0
    return f"{v:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".") + sufijo

# ================= Clasificación por SIGNO (ΔVUR) =================
# Ajustá los umbrales si querés (en ARS)
def clasificar_por_signo(delta):
    if pd.isna(delta):
        return "🔵 Neutra / mejora"
    if delta <= -10000:
        return "🔴 Alta pérdida"
    elif delta < -2000:
        return "🟡 Pérdida moderada"
    elif delta < 0:
        return "🟢 Pérdida leve"
    else:
        return "🔵 Neutra / mejora"

col = {
    "🔴 Alta pérdida": "#c92a2a",
    "🟡 Pérdida moderada": "#f08c00",
    "🟢 Pérdida leve": "#2f9e44",
    "🔵 Neutra / mejora": "#1c7ed6",
}

# ================= Preparación fija =================
# Pedanía alineada al X_test
df_base_test = df.loc[X_test.index].copy()
df_base_test["Pedania_norm"] = df_base_test["Pedania"].apply(normalizar_txt)

# Pedanías de interés
ped = pedanias_union.copy()
ped["Pedania_norm"] = ped["nombre"].apply(normalizar_txt)
interes_norm = set(normalizar_txt(x) for x in pedanias_interes)
ped = ped[ped["Pedania_norm"].isin(interes_norm)].copy()

# Centro del mapa
depto_union_5346 = union.to_crs(5346)
centro = depto_union_5346.geometry.centroid.iloc[0]
centro = gpd.GeoSeries([centro], crs=5346).to_crs(4326).iloc[0]

# ================= Helper para capas extra (red vial/hidrología/radios) =================
def add_gdf_layer(m, gdf, name, color, weight=2, fill=False, fill_opacity=0.3,
                  tooltip_fields=None, popup_fields=None):
    if gdf is None or gdf.empty:
        return

    gdf_clean = gdf[gdf.geometry.type.isin(
        ["LineString", "MultiLineString", "Polygon", "MultiPolygon"]
    )].explode(index_parts=False).reset_index(drop=True)

    if gdf_clean.empty:
        return

    folium.GeoJson(
        gdf_clean.to_crs(4326),
        name=name,
        style_function=lambda x: {
            "color": color,
            "weight": weight,
            "fillOpacity": fill_opacity if fill else 0,
        },
        tooltip=folium.GeoJsonTooltip(fields=tooltip_fields) if tooltip_fields else None,
        popup=folium.GeoJsonPopup(fields=popup_fields) if popup_fields else None
    ).add_to(m)

# ================= Helper para semáforo (polígonos pedanías) =================
def add_geojson_semaforo(m, gdf, name, fillColor, layer_obj=None):
    if gdf is None or gdf.empty:
        return

    gdf = gdf.to_crs(4326)

    gj = folium.GeoJson(
        gdf,
        name=name,
        style_function=lambda feat, c=fillColor: {
            "color": "black",
            "weight": 2,
            "fillColor": c,
            "fillOpacity": 0.30  # transparente para ver rutas/ríos arriba
        },
        tooltip=folium.GeoJsonTooltip(
            fields=["nombre", "delta_txt", "sens_por_unidad_txt", "cat"],
            aliases=["Pedanía", "ΔVUR (nuevo - base)", "ΔVUR por 1 unidad de PDSI", "Clase"]
        ),
        popup=folium.GeoJsonPopup(
            fields=["nombre", "delta_txt", "sens_por_unidad_txt", "cat"],
            aliases=["Pedanía", "ΔVUR (nuevo - base)", "ΔVUR por 1 unidad de PDSI", "Clase"]
        )
    )

    if layer_obj is None:
        gj.add_to(m)
    else:
        gj.add_to(layer_obj)

# ================= Función principal =================
def construir_mapa_sens(pdsi_base, pdsi_nuevo):

    # Validación
    if pdsi_base < -4 or pdsi_base > 4 or pdsi_nuevo < -4 or pdsi_nuevo > 4:
        raise ValueError("PDSI debe estar entre -4 y 4.")
    if pdsi_nuevo == pdsi_base:
        raise ValueError("PDSI_base y PDSI_nuevo no pueden ser iguales.")

    # 1) Predicciones para ambos escenarios (mismas observaciones)
    Xb = X_test.copy(); Xb["PDSI_promedio"] = pdsi_base
    Xn = X_test.copy(); Xn["PDSI_promedio"] = pdsi_nuevo

    Xb_prep = preprocessor.transform(Xb)
    Xn_prep = preprocessor.transform(Xn)

    pred_b = modelo_final.predict(Xb_prep)
    pred_n = modelo_final.predict(Xn_prep)

    # 2) Cambio por observación y sensibilidad por unidad
    delta_obs = pred_n - pred_b
    delta_pdsi = (pdsi_nuevo - pdsi_base)
    sens_por_unidad = delta_obs / delta_pdsi

    # 3) Promedio por pedanía
    df_sens = pd.DataFrame({
        "Pedania_norm": df_base_test["Pedania_norm"].to_numpy(),
        "delta": delta_obs,
        "sens_unidad": sens_por_unidad
    })

    ped_stats = (df_sens.groupby("Pedania_norm")[["delta", "sens_unidad"]]
                        .mean()
                        .reset_index())

    # 4) Unir a geometría
    g = ped.merge(ped_stats, on="Pedania_norm", how="left")
    g["delta"] = g["delta"].fillna(0.0)
    g["sens_unidad"] = g["sens_unidad"].fillna(0.0)

    g["delta_txt"] = g["delta"].map(lambda v: fmt_ar(v, " ARS"))
    g["sens_por_unidad_txt"] = g["sens_unidad"].map(lambda v: fmt_ar(v, " ARS / PDSI"))

    # 5) Clasificar por SIGNO/MAGNITUD de ΔVUR
    g["cat"] = g["delta"].apply(clasificar_por_signo)

    # ================= Mapa =================
    m = folium.Map(location=[centro.y, centro.x], zoom_start=9, tiles=None, control_scale=True)

    folium.TileLayer("OpenStreetMap", name="OpenStreetMap").add_to(m)
    folium.TileLayer(
        tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        attr="Esri",
        name="Esri Satellite",
        overlay=False,
        control=True
    ).add_to(m)

    # ORDEN: Departamento -> Semáforo -> Redes arriba
    add_gdf_layer(m, depto_union_5346, "Departamento UNIÓN", "black", weight=3)

    # Semáforo por categorías
    for cat, color in col.items():
        fg = folium.FeatureGroup(name=f"Vulnerabilidad — {cat}", show=True)
        sub = g[g["cat"] == cat].copy()
        if not sub.empty:
            add_geojson_semaforo(m, sub, cat, fillColor=color, layer_obj=fg)
            fg.add_to(m)

    # Capas extra ARRIBA (si existen en tu notebook)
    if "nacional_union" in globals():
        add_gdf_layer(m, nacional_union, "Red vial nacional", "black", weight=3)
    if "provincial_union" in globals():
        add_gdf_layer(m, provincial_union, "Red vial provincial", "gray", weight=2)
    if "regional_union" in globals():
        add_gdf_layer(m, regional_union, "Red vial regional", "brown", weight=2)

    if "gdf_cursos" in globals():
        add_gdf_layer(m, gdf_cursos, "Cursos de agua", "blue", weight=2)
    if "gdf_canales" in globals():
        add_gdf_layer(m, gdf_canales, "Canales de riego", "cyan", weight=2)
    if "gdf_acueductos" in globals():
        add_gdf_layer(m, gdf_acueductos, "Acueductos", "purple", weight=2)
    if "gdf_embalses" in globals():
        add_gdf_layer(m, gdf_embalses, "Embalses", "lightblue", weight=2, fill=True, fill_opacity=0.35)
    if "gdf_cuerpos" in globals():
        add_gdf_layer(m, gdf_cuerpos, "Cuerpos de Agua Naturales", "aqua", weight=2, fill=True, fill_opacity=0.35)

    # Radios urbanos
    if "radios_urbanos" in globals():
        radios_union = radios_urbanos.to_crs(5346)
        try:
            gdf_radios_urbanos = gpd.clip(radios_union, depto_union_5346)
        except Exception:
            gdf_radios_urbanos = gpd.sjoin(
                radios_union, depto_union_5346[["geometry"]],
                how="inner", predicate="intersects"
            ).drop(columns="index_right")

        if gdf_radios_urbanos is not None and (not gdf_radios_urbanos.empty):
            add_gdf_layer(
                m, gdf_radios_urbanos, "Radios urbanos", "red",
                weight=2, fill=True, fill_opacity=0.10,
                tooltip_fields=["nombre"] if "nombre" in gdf_radios_urbanos.columns else None,
                popup_fields=["nombre"] if "nombre" in gdf_radios_urbanos.columns else None
            )

    folium.LayerControl(collapsed=False, position="bottomright").add_to(m)

    # ===== Leyenda unificada (Semáforo + Capas) =====
    legend_unificada = """
    <div style="
        position: fixed;
        bottom: 30px; left: 30px;
        border:2px solid grey;
        z-index:9999;
        font-size:13px;
        background-color:white;
        padding: 10px;
        border-radius:6px;
        box-shadow: 2px 2px 6px rgba(0,0,0,0.3);
    ">
    <b>Leyenda</b><br><br>

    <b>Vulnerabilidad (ΔVUR = nuevo − base)</b><br>
    <span style="color:#c92a2a;">&#9632;</span> 🔴 Alta pérdida<br>
    <span style="color:#f08c00;">&#9632;</span> 🟡 Pérdida moderada<br>
    <span style="color:#2f9e44;">&#9632;</span> 🟢 Pérdida leve<br>
    <span style="color:#1c7ed6;">&#9632;</span> 🔵 Neutra / mejora<br>

    <hr style="margin:6px 0;">

    <b>Capas</b><br>
    <span style="color:black;">&#8212;&#8212;</span> Red vial nacional<br>
    <span style="color:gray;">&#8212;&#8212;</span> Red vial provincial<br>
    <span style="color:brown;">&#8212;&#8212;</span> Red vial regional<br>
    <span style="color:blue;">&#8212;&#8212;</span> Cursos de agua<br>
    <span style="color:cyan;">&#8212;&#8212;</span> Canales de riego<br>
    <span style="color:purple;">&#8212;&#8212;</span> Acueductos<br>
    <span style="color:deepskyblue;">&#9632;</span> Embalses<br>
    <span style="color:aqua;">&#9632;</span> Cuerpos de agua naturales<br>
    <span style="color:red;">&#9632;</span> Radios urbanos<br>
    </div>
    """
    m.get_root().html.add_child(folium.Element(legend_unificada))

    # Título
    title_html = f"""
    <h3 align="center" style="font-size:20px; margin-top: 10px;">
    Sensibilidad del VUR ante cambio en PDSI (simulación contrafáctica)<br>
    <span style="font-size:14px;">
    Comparación: PDSI_base = {pdsi_base:.2f} → PDSI_nuevo = {pdsi_nuevo:.2f}, manteniendo constantes anio e IP_prom_area
    </span>
    </h3>
    """
    m.get_root().html.add_child(folium.Element(title_html))

    # Norte
    north_html = """
    <div style="
        position: fixed;
        top: 70px; right: 50px;
        z-index:9999;
        text-align:center;
        background-color: rgba(255,255,255,0.8);
        padding: 6px;
        border:1px solid #666;
        border-radius: 6px;
        font-size: 14px;
    ">
    <b>N</b><br>
    <span style="font-size:22px;">↑</span>
    </div>
    """
    m.get_root().html.add_child(folium.Element(north_html))

    return m

# ================= Interfaz =================
out = widgets.Output()

pdsi_base_in = widgets.FloatText(value=-1.0, description="PDSI base:", layout=widgets.Layout(width="220px"))
pdsi_new_in  = widgets.FloatText(value=-2.0, description="PDSI nuevo:", layout=widgets.Layout(width="220px"))

ayuda = widgets.HTML("<span style='font-size:13px; color:gray;'>Ingrese valores entre -4 y 4. El mapa se actualiza al cambiar.</span>")

def refrescar(_=None):
    with out:
        clear_output(wait=True)
        try:
            display(construir_mapa_sens(pdsi_base_in.value, pdsi_new_in.value))
        except Exception as e:
            print("⚠️", e)

pdsi_base_in.observe(refrescar, names="value")
pdsi_new_in.observe(refrescar, names="value")

display(widgets.HBox([pdsi_base_in, pdsi_new_in]))
display(ayuda)
display(out)

refrescar()

"""La simulación contrafáctica que evalúa el paso de un escenario por ejemplo PDSI = 1 (condición ligeramente húmeda) a PDSI = −2 (sequía moderada) evidencia una reducción significativa .
Este resultado indica que ante un deterioro leve en las condiciones climáticas (incremento de la sequía en una unidad PDSI), el valor unitario rural en la pedanía Loboy experimenta una disminución promedio cercana a los $4.600 ARS. Esto evidencia una sensibilidad económica directa del mercado de tierras frente a variaciones en el estrés hídrico.

La simulación contrafáctica que evalúa el paso de un escenario PDSI = 1 a PDSI = −4 (sequía extrema) evidencia una reducción promedio del valor unitario rural cercana a los $43.910 ARS en la pedanía Loboy. Este resultado sugiere una elevada sensibilidad económica ante escenarios climáticos extremos, y confirma que el impacto marginal de la sequía sobre el valor del suelo se intensifica en condiciones de mayor estrés hídrico.

#Gemelo Digital creado
"""

def evaluar_gemelo_digital(
    imita_estructura,
    imita_contexto,
    imita_comportamiento,
    actualiza_dinamico,
    usa_datos_fisicos,
    capacidad_predictiva,
    informa_decisiones,
    retroalimentacion_bidireccional,
    evidencia=None
):
    """
    Evalúa el nivel de gemelo digital en base a criterios booleanos.
    """

    criterios = {
        "Estructura": imita_estructura,
        "Contexto": imita_contexto,
        "Comportamiento": imita_comportamiento,
        "Actualización dinámica": actualiza_dinamico,
        "Datos físicos": usa_datos_fisicos,
        "Capacidad predictiva": capacidad_predictiva,
        "Soporte a decisiones": informa_decisiones,
        "Bidireccionalidad": retroalimentacion_bidireccional
    }

    # Tabla base
    tabla = pd.DataFrame({
        "Criterio": list(criterios.keys()),
        "Cumple": list(criterios.values())
    })

    # Agregar evidencia si existe
    if evidencia:
        tabla["Evidencia"] = tabla["Criterio"].map(evidencia)

    # ================= CLASIFICACIÓN =================
    if retroalimentacion_bidireccional:
        tipo = "Gemelo Digital Bidireccional"

    elif capacidad_predictiva and informa_decisiones:
        tipo = "Gemelo Digital Unidireccional Analítico (Nivel 3)"

    elif imita_comportamiento:
        tipo = "Gemelo Digital Diagnóstico/Dinámico (Nivel 2)"

    elif imita_estructura and imita_contexto:
        tipo = "Gemelo Digital Descriptivo (Nivel 1)"

    else:
        tipo = "Modelo digital básico (Nivel 0)"

    resumen = {
        "clasificacion_tipo": tipo,
        "criterios_cumplidos": sum(criterios.values()),
        "total_criterios": len(criterios)
    }

    return tabla, resumen

# =========================================================
# 2) Inferir nivel 0..4 a partir del resumen + entradas
# =========================================================
def inferir_nivel(resumen: dict, entradas: dict) -> int:
    """
    Devuelve un nivel 0..4 según la clasificación y criterios del prototipo.
    """

    tipo = str(resumen.get("clasificacion_tipo", "") or "").lower()

    # Nivel 4: bidireccional
    if "bidireccional" in tipo or entradas.get("retroalimentacion_bidireccional", False):
        return 4

    # Nivel 3: predictivo validado
    if (
        ("unidireccional" in tipo and "anal" in tipo)
        or (entradas.get("capacidad_predictiva", False) and entradas.get("informa_decisiones", False))
    ):
        return 3

    # Nivel 2: diagnóstico/dinámico
    if entradas.get("capacidad_predictiva", False) or entradas.get("imita_comportamiento", False):
        return 2

    # Nivel 1: descriptivo
    if entradas.get("imita_estructura", False) and entradas.get("imita_contexto", False):
        return 1

    # Nivel 0: sin evidencias
    return 0


# =========================================================
# 3) Etiquetas del nivel
# =========================================================
def obtener_nombre_nivel(nivel: int) -> str:
    niveles = {
        0: "Nivel 0: Sin evidencias",
        1: "Nivel 1: Descriptivo",
        2: "Nivel 2: Diagnóstico / Dinámico",
        3: "Nivel 3: Predictivo validado",
        4: "Nivel 4: Bidireccional"
    }
    return niveles.get(nivel, "Nivel desconocido")


def obtener_interpretacion_nivel(nivel: int) -> str:
    interpretaciones = {
        0: "No hay evidencias suficientes para considerarlo un gemelo digital.",
        1: "Representa la estructura y el contexto del sistema, pero sin análisis predictivo.",
        2: "Incluye análisis o modelado del comportamiento, aunque sin soporte decisional fuerte.",
        3: "Permite simular escenarios y apoyar decisiones territoriales de forma validada.",
        4: "Incorpora retroalimentación bidireccional con capacidad de actuación sobre el sistema físico."
    }
    return interpretaciones.get(nivel, "")


# =========================================================
# 4) Cuadrito estético resumen
# =========================================================
def mostrar_cuadro_nivel(resumen: dict, nivel: int):
    """
    Muestra un cuadro resumen bonito con el nivel inferido.
    """
    clasificacion = resumen.get("clasificacion_tipo", "No especificada")
    interpretacion = obtener_interpretacion_nivel(nivel)
    nombre_nivel = obtener_nombre_nivel(nivel)

    df_cuadro = pd.DataFrame({
        "Ítem": [
            "Clasificación del prototipo",
            "Nivel alcanzado",
            "Interpretación"
        ],
        "Detalle": [
            clasificacion,
            nombre_nivel,
            interpretacion
        ]
    })

    styled = (
        df_cuadro.style
        .hide(axis="index")
        .set_properties(**{
            "text-align": "left",
            "font-size": "12px",
            "padding": "8px"
        })
        .set_table_styles([
            {"selector": "th",
             "props": [("background-color", "#1f4e79"),
                       ("color", "white"),
                       ("font-weight", "bold"),
                       ("text-align", "center"),
                       ("font-size", "12px")]},
            {"selector": "td",
             "props": [("border", "1px solid #d0d7de")]},
            {"selector": "table",
             "props": [("border-collapse", "collapse"),
                       ("width", "100%"),
                       ("margin", "10px 0")]}
        ])
    )

    display(styled)


# =========================================================
# 5) Barra de niveles mejorada
# =========================================================
def graficar_niveles_gemelo_digital(nivel: int, titulo="Niveles de madurez del gemelo digital"):
    """
    Dibuja una barra segmentada por niveles y resalta el nivel alcanzado.
    """
    labels = [
        "Nivel 0\nSin evidencias",
        "Nivel 1\nDescriptivo",
        "Nivel 2\nDiagnóstico /\nDinámico",
        "Nivel 3\nPredictivo\nvalidado",
        "Nivel 4\nBidireccional"
    ]

    colors = ["#d9d9d9", "#9ecae1", "#6baed6", "#3182bd", "#08519c"]
    edge = "#1f1f1f"

    fig, ax = plt.subplots(figsize=(13, 3.6))

    x0, y0 = 0, 0.9
    h = 0.6

    # segmentos
    for i in range(5):
        ax.add_patch(
            Rectangle(
                (x0 + i, y0), 1, h,
                facecolor=colors[i],
                edgecolor=edge,
                linewidth=1.4
            )
        )

    # borde externo
    ax.add_patch(Rectangle((x0, y0), 5, h, fill=False, edgecolor=edge, linewidth=1.6))

    # etiquetas
    for i, lab in enumerate(labels):
        ax.text(
            x0 + i + 0.5,
            y0 - 0.14,
            lab,
            ha="center",
            va="top",
            fontsize=10
        )

    # línea del nivel
    nivel = int(max(0, min(4, nivel)))
    x_linea = x0 + nivel + 0.5

    ax.plot(
        [x_linea, x_linea],
        [y0, y0 + h],
        linestyle="--",
        linewidth=2.4,
        color="red"
    )

    ax.text(
        x_linea,
        y0 + h + 0.16,
        f"Ubicación del prototipo\nNivel {nivel}",
        color="red",
        fontsize=10,
        ha="center",
        va="bottom",
        fontweight="bold"
    )

    # título
    ax.text(
        2.5,
        y0 + h + 0.48,
        titulo,
        ha="center",
        va="bottom",
        fontsize=14,
        fontweight="bold"
    )

    ax.set_xlim(-0.2, 5.2)
    ax.set_ylim(0, 2.1)
    ax.axis("off")
    plt.tight_layout()
    plt.show()


# =========================================================
# 6) Ejemplo de uso
# =========================================================
entradas = dict(
    imita_estructura=True,
    imita_contexto=True,
    imita_comportamiento=True,
    actualiza_dinamico=False,
    usa_datos_fisicos=True,
    capacidad_predictiva=True,
    informa_decisiones=True,
    retroalimentacion_bidireccional=False
)

tabla, resumen = evaluar_gemelo_digital(
    **entradas,
    evidencia={
        "estructura": "Capas territoriales (departamento, pedanías) y parcelas con atributos integrados; representación espacial del sistema.",
        "contexto": "Incorpora contexto temporal (año) y territorial (pedanía / Departamento Unión) en el análisis y los mapas.",
        "comportamiento": "El modelo aprende la relación entre VUR, PDSI, IP y año; además evalúa cambios bajo distintos escenarios.",
        "actualiza_dinamico": "La ejecución es por demanda en notebook. Para ser dinámico debería automatizar la actualización de datos.",
        "datos_fisicos": "Utiliza datos observados: valuaciones, índice de sequía PDSI e índice de productividad del suelo.",
        "predictiva": "Incluye modelos de aprendizaje automático y simulación contrafáctica modificando únicamente el PDSI.",
        "decisiones": "Genera mapas de sensibilidad por pedanía, útiles para interpretación territorial y apoyo a decisiones.",
        "bidireccional": "No implementado: no existe un bucle de retroalimentación virtual ↔ físico."
    }
)

# Mostrar tabla original
display(tabla)

print("\n=== RESUMEN ===")
for k, v in resumen.items():
    print(f"- {k}: {v}")

# Inferir nivel
nivel = inferir_nivel(resumen, entradas)

# Mostrar cuadrito estético
mostrar_cuadro_nivel(resumen, nivel)

# Mostrar gráfico de niveles
graficar_niveles_gemelo_digital(nivel)